# Generated by Django 5.0.6 on 2024-06-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotDataUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('site_name', models.TextField(blank=True, null=True)),
                ('site_code', models.TextField(blank=True, null=True)),
                ('image_Cycle_Slip_PLOT', models.ImageField(upload_to='media/up')),
                ('image_MP_PLOT', models.ImageField(upload_to='media/up')),
                ('image_Percentage_Observation', models.ImageField(upload_to='media/up')),
                ('image_TS_PLOT', models.ImageField(upload_to='media/up')),
                ('coordinates', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
